version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_SESSION: ${PHP_XDEBUG_SESSION:-0}
      XDEBUG_PROFILE: ${PHP_XDEBUG_PROFILE:-0}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=kma}
    env_file:
     - .env
  php-fpm-consumer:
    build:
      context: ./docker/php
      dockerfile: DockerfileConsumer
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
  db:
    image: mariadb:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 15672:15672
      - 5672:5672

  ch-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9004:9004"
    environment:
      - CLICKHOUSE_DB=kma
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - ./docker/clickhouse:/docker-entrypoint-initdb.d